# -*- coding: utf-8 -*-
"""newGithub_Indian_Library_10_10_Mic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9ZGdSTkmXGYhB03be8fPd1m_j3sNFJX
"""

!pip install playwright
!playwright install
!pip install getindianname